import { deepFreeze } from "../core/math.js";
import { MOVE_CLIPS } from "../animation/move-clips.js";

function contact(limb, start, end, x, y = 0, id = "") {
  return { id: id || `${limb}-${start}`, limb, start, end, point: [x, y] };
}

const FEET_STANDING = [
  contact("leftFoot", 0, 0.18, -6),
  contact("rightFoot", 0, 0.18, 6),
  contact("leftFoot", 0.48, 0.7, -4),
  contact("rightFoot", 0.78, 1, 6),
];

const FLOOR_ALTERNATE = [
  contact("leftPaw", 0, 0.52, -13),
  contact("rightPaw", 0.18, 0.82, 13),
  contact("leftFoot", 0, 0.2, -7),
  contact("rightFoot", 0, 0.18, 14),
  contact("leftFoot", 0.5, 0.72, 9),
  contact("rightFoot", 0.64, 0.9, 14),
];

function move(definition) {
  const family = definition.family;
  const defaults = {
    difficulty: 0.2,
    durationBeats: 2,
    minimumDuration: 0.5,
    loopLength: 0,
    loopable: false,
    entryTags: [],
    exitTags: [],
    eligiblePrecedingFamilies: ["idle", family],
    contacts: [],
    centerOfMassCurve: [[0, 0, -18], [1, 0, -18]],
    rootMotionCurve: [[0, 0, 0], [1, 0, 0]],
    facingBehavior: "input",
    mirrorable: true,
    staminaCost: 2,
    staminaDrainPerBeat: 0,
    balanceDemand: 0,
    cancelWindows: [[0.72, 1]],
    accentWindows: [0, 0.5, 1],
    extensionInput: "",
    validFollowUps: [],
    failureRecovery: "basicGoDown",
    scoreProperties: {
      base: 20,
      musicality: 0.5,
      vocabulary: 0.5,
      originality: 0.4,
      technique: 0.3,
      execution: 0.6,
    },
    animationClip: definition.id,
    poseCadence: MOVE_CLIPS[definition.id]?.cadence ?? 15,
    soundEvents: [{ at: 0, id: "moveStart" }],
    crowdResponsePotential: 0.2,
    ...definition,
  };
  if (!MOVE_CLIPS[defaults.animationClip]) {
    throw new Error(`Move ${defaults.id} references missing clip ${defaults.animationClip}.`);
  }
  return defaults;
}

const TOPROCK_FOLLOWUPS = ["basicRock", "indianStep", "kickStep", "crossStep", "salsaStep", "basicGoDown", "kneeDrop", "sweepDown", "spinDown"];
const FLOOR_FOLLOWUPS = ["twoStep", "threeStep", "sixStep", "cc", "sweep", "coffeeGrinder", "backspin", "swipe", "windmill", "flare", "babyFreeze", "chairFreeze", "turtleFreeze", "headstandFreeze", "cleanGetUp"];
const POWER_FOLLOWUPS = ["backspin", "swipe", "windmill", "flare", "headspin", "babyFreeze", "chairFreeze", "turtleFreeze", "headstandFreeze"];
const FREEZE_FOLLOWUPS = ["cleanGetUp", "twoStep", "threeStep", "sixStep"];

export const MOVE_CATALOG = deepFreeze({
  basicRock: move({
    id: "basicRock",
    displayName: "BASIC ROCK",
    family: "toprock",
    difficulty: 0.1,
    durationBeats: 2,
    minimumDuration: 0.5,
    loopLength: 2,
    loopable: true,
    entryTags: ["standing"],
    exitTags: ["standing", "goDownReady"],
    eligiblePrecedingFamilies: ["idle", "toprock", "recovery"],
    contacts: FEET_STANDING,
    centerOfMassCurve: [[0, 0, -20], [0.25, -4, -20], [0.5, 0, -21], [0.75, 4, -20], [1, 0, -20]],
    staminaCost: 0,
    staminaDrainPerBeat: -2.2,
    validFollowUps: TOPROCK_FOLLOWUPS,
    scoreProperties: { base: 18, musicality: 0.9, vocabulary: 0.35, originality: 0.22, technique: 0.18, execution: 0.72 },
    crowdResponsePotential: 0.12,
  }),
  indianStep: move({
    id: "indianStep",
    displayName: "INDIAN STEP",
    family: "toprock",
    difficulty: 0.2,
    entryTags: ["standing"],
    exitTags: ["standing", "goDownReady"],
    contacts: FEET_STANDING,
    staminaCost: 1,
    validFollowUps: TOPROCK_FOLLOWUPS,
    scoreProperties: { base: 24, musicality: 0.82, vocabulary: 0.52, originality: 0.42, technique: 0.28, execution: 0.68 },
    crowdResponsePotential: 0.18,
  }),
  kickStep: move({
    id: "kickStep",
    displayName: "KICK STEP",
    family: "toprock",
    difficulty: 0.25,
    entryTags: ["standing"],
    exitTags: ["standing", "goDownReady"],
    contacts: FEET_STANDING,
    staminaCost: 1.2,
    validFollowUps: TOPROCK_FOLLOWUPS,
    scoreProperties: { base: 26, musicality: 0.9, vocabulary: 0.5, originality: 0.46, technique: 0.32, execution: 0.65 },
    crowdResponsePotential: 0.2,
  }),
  crossStep: move({
    id: "crossStep",
    displayName: "CROSS STEP",
    family: "toprock",
    difficulty: 0.3,
    entryTags: ["standing"],
    exitTags: ["standing", "goDownReady"],
    contacts: FEET_STANDING,
    staminaCost: 1.4,
    validFollowUps: TOPROCK_FOLLOWUPS,
    scoreProperties: { base: 28, musicality: 0.78, vocabulary: 0.58, originality: 0.5, technique: 0.4, execution: 0.62 },
    crowdResponsePotential: 0.22,
  }),
  salsaStep: move({
    id: "salsaStep",
    displayName: "SALSA STEP",
    family: "toprock",
    difficulty: 0.34,
    entryTags: ["standing"],
    exitTags: ["standing", "goDownReady"],
    contacts: FEET_STANDING,
    staminaCost: 1.5,
    validFollowUps: TOPROCK_FOLLOWUPS,
    scoreProperties: { base: 31, musicality: 0.86, vocabulary: 0.6, originality: 0.62, technique: 0.38, execution: 0.6 },
    crowdResponsePotential: 0.24,
  }),

  basicGoDown: move({
    id: "basicGoDown",
    displayName: "GO DOWN",
    family: "transition",
    difficulty: 0.18,
    durationBeats: 1,
    minimumDuration: 0.5,
    entryTags: ["standing"],
    exitTags: ["floor", "twoHandsAvailable", "powerReady", "freezeReady"],
    eligiblePrecedingFamilies: ["idle", "toprock"],
    contacts: [
      contact("leftFoot", 0, 0.5, -7),
      contact("rightFoot", 0, 0.48, 8),
      contact("leftPaw", 0.48, 1, -13),
      contact("rightFoot", 0.58, 1, 13),
    ],
    centerOfMassCurve: [[0, 0, -20], [0.5, -2, -12], [1, 0, -10]],
    staminaCost: 1.5,
    cancelWindows: [[0.82, 1]],
    accentWindows: [0, 1],
    validFollowUps: FLOOR_FOLLOWUPS,
    scoreProperties: { base: 26, musicality: 0.78, vocabulary: 0.44, originality: 0.3, technique: 0.3, execution: 0.78 },
    crowdResponsePotential: 0.16,
  }),
  kneeDrop: move({
    id: "kneeDrop",
    displayName: "KNEE DROP",
    family: "transition",
    difficulty: 0.38,
    durationBeats: 1,
    entryTags: ["standing"],
    exitTags: ["floor", "twoHandsAvailable", "powerReady", "freezeReady"],
    eligiblePrecedingFamilies: ["toprock"],
    contacts: [contact("leftFoot", 0, 0.5, -8), contact("rightFoot", 0, 0.48, 7), contact("leftFoot", 0.55, 1, -12), contact("rightFoot", 0.55, 1, 5)],
    staminaCost: 3,
    validFollowUps: FLOOR_FOLLOWUPS,
    scoreProperties: { base: 42, musicality: 0.7, vocabulary: 0.55, originality: 0.5, technique: 0.58, execution: 0.7 },
    crowdResponsePotential: 0.34,
  }),
  sweepDown: move({
    id: "sweepDown",
    displayName: "SWEEP DOWN",
    family: "transition",
    difficulty: 0.46,
    durationBeats: 1.5,
    entryTags: ["standing"],
    exitTags: ["floor", "twoHandsAvailable", "powerReady", "freezeReady"],
    eligiblePrecedingFamilies: ["toprock"],
    contacts: [contact("leftFoot", 0, 0.28, -8), contact("leftPaw", 0.24, 1, -14), contact("rightFoot", 0.68, 1, -14)],
    staminaCost: 4,
    validFollowUps: FLOOR_FOLLOWUPS,
    scoreProperties: { base: 50, musicality: 0.72, vocabulary: 0.58, originality: 0.62, technique: 0.65, execution: 0.68 },
    crowdResponsePotential: 0.4,
  }),
  spinDown: move({
    id: "spinDown",
    displayName: "SPIN DOWN",
    family: "transition",
    difficulty: 0.52,
    durationBeats: 1.5,
    entryTags: ["standing"],
    exitTags: ["floor", "twoHandsAvailable", "powerReady", "freezeReady"],
    eligiblePrecedingFamilies: ["toprock"],
    contacts: [contact("leftFoot", 0, 0.3, -8), contact("rightFoot", 0, 0.32, 8), contact("leftPaw", 0.55, 1, -13), contact("rightFoot", 0.7, 1, 12)],
    staminaCost: 4.5,
    validFollowUps: FLOOR_FOLLOWUPS,
    scoreProperties: { base: 56, musicality: 0.68, vocabulary: 0.6, originality: 0.65, technique: 0.72, execution: 0.64 },
    crowdResponsePotential: 0.45,
  }),
  cleanGetUp: move({
    id: "cleanGetUp",
    displayName: "CLEAN GET-UP",
    family: "recovery",
    difficulty: 0.24,
    durationBeats: 1,
    entryTags: ["floor"],
    exitTags: ["standing", "goDownReady"],
    eligiblePrecedingFamilies: ["idle", "footwork", "freeze", "power", "recovery"],
    contacts: [contact("leftPaw", 0, 0.35, -13), contact("rightPaw", 0, 0.5, 11), contact("leftFoot", 0.2, 1, -7), contact("rightFoot", 0.45, 1, 8)],
    staminaCost: 0,
    staminaDrainPerBeat: -1.2,
    accentWindows: [0.8, 1],
    validFollowUps: TOPROCK_FOLLOWUPS,
    scoreProperties: { base: 34, musicality: 0.72, vocabulary: 0.44, originality: 0.28, technique: 0.38, execution: 0.9 },
    crowdResponsePotential: 0.28,
  }),

  twoStep: move({
    id: "twoStep", displayName: "2-STEP", family: "footwork", difficulty: 0.22, durationBeats: 2,
    entryTags: ["floor"], exitTags: ["floor", "twoHandsAvailable", "powerReady", "freezeReady"],
    eligiblePrecedingFamilies: ["idle", "transition", "footwork", "freeze"], contacts: FLOOR_ALTERNATE, staminaCost: 2.5,
    validFollowUps: FLOOR_FOLLOWUPS,
    scoreProperties: { base: 34, musicality: 0.72, vocabulary: 0.5, originality: 0.34, technique: 0.4, execution: 0.68 }, crowdResponsePotential: 0.2,
  }),
  threeStep: move({
    id: "threeStep", displayName: "3-STEP", family: "footwork", difficulty: 0.3, durationBeats: 2,
    entryTags: ["floor"], exitTags: ["floor", "twoHandsAvailable", "powerReady", "freezeReady"],
    eligiblePrecedingFamilies: ["idle", "transition", "footwork", "freeze"], contacts: FLOOR_ALTERNATE, staminaCost: 3.5,
    validFollowUps: FLOOR_FOLLOWUPS,
    scoreProperties: { base: 42, musicality: 0.74, vocabulary: 0.55, originality: 0.4, technique: 0.48, execution: 0.66 }, crowdResponsePotential: 0.25,
  }),
  sixStep: move({
    id: "sixStep",
    displayName: "6-STEP",
    family: "footwork",
    difficulty: 0.38,
    durationBeats: 4,
    minimumDuration: 1,
    loopLength: 4,
    loopable: true,
    entryTags: ["floor"],
    exitTags: ["floor", "twoHandsAvailable", "powerReady", "freezeReady"],
    eligiblePrecedingFamilies: ["idle", "transition", "footwork", "freeze"],
    contacts: [
      contact("leftPaw", 0, 0.52, -13), contact("rightPaw", 0.13, 0.88, 13),
      contact("leftFoot", 0, 0.08, -7), contact("rightFoot", 0, 0.18, 14),
      contact("leftFoot", 0.48, 0.7, 9), contact("rightFoot", 0.64, 0.88, 14),
      contact("leftPaw", 0.82, 1, -13, 0, "leftPaw-return"),
    ],
    centerOfMassCurve: [[0, 0, -10], [0.25, 2, -10], [0.5, 0, -9], [0.75, -2, -10], [1, 0, -10]],
    staminaCost: 5,
    staminaDrainPerBeat: 0.8,
    cancelWindows: [[0.46, 0.55], [0.78, 1]],
    accentWindows: [0, 0.5, 1],
    extensionInput: "action",
    validFollowUps: FLOOR_FOLLOWUPS,
    scoreProperties: { base: 78, musicality: 0.78, vocabulary: 0.72, originality: 0.5, technique: 0.62, execution: 0.72 },
    crowdResponsePotential: 0.42,
  }),
  cc: move({
    id: "cc", displayName: "CC", family: "footwork", difficulty: 0.42, durationBeats: 2,
    entryTags: ["floor"], exitTags: ["floor", "twoHandsAvailable", "powerReady", "freezeReady"],
    eligiblePrecedingFamilies: ["footwork", "transition"], contacts: FLOOR_ALTERNATE, staminaCost: 4,
    validFollowUps: FLOOR_FOLLOWUPS,
    scoreProperties: { base: 52, musicality: 0.76, vocabulary: 0.7, originality: 0.64, technique: 0.58, execution: 0.66 }, crowdResponsePotential: 0.34,
  }),
  sweep: move({
    id: "sweep", displayName: "SWEEP", family: "footwork", difficulty: 0.48, durationBeats: 2,
    entryTags: ["floor"], exitTags: ["floor", "twoHandsAvailable", "powerReady", "freezeReady"],
    eligiblePrecedingFamilies: ["footwork", "transition"], contacts: FLOOR_ALTERNATE, staminaCost: 5,
    validFollowUps: FLOOR_FOLLOWUPS,
    scoreProperties: { base: 62, musicality: 0.7, vocabulary: 0.66, originality: 0.68, technique: 0.7, execution: 0.64 }, crowdResponsePotential: 0.42,
  }),
  coffeeGrinder: move({
    id: "coffeeGrinder", displayName: "COFFEE GRINDER", family: "footwork", difficulty: 0.56, durationBeats: 2,
    loopLength: 2, loopable: true, entryTags: ["floor"], exitTags: ["floor", "twoHandsAvailable", "powerReady", "freezeReady"],
    eligiblePrecedingFamilies: ["footwork", "transition"], contacts: [contact("leftPaw", 0, 1, -14), contact("rightPaw", 0.42, 0.72, 13)],
    staminaCost: 6, staminaDrainPerBeat: 1.4, extensionInput: "style", validFollowUps: FLOOR_FOLLOWUPS,
    scoreProperties: { base: 74, musicality: 0.7, vocabulary: 0.72, originality: 0.76, technique: 0.75, execution: 0.6 }, crowdResponsePotential: 0.5,
  }),

  backspin: move({
    id: "backspin", displayName: "BACKSPIN", family: "power", difficulty: 0.48, durationBeats: 2,
    loopLength: 2, loopable: true, entryTags: ["floor", "powerReady"], exitTags: ["floor", "powerReady", "freezeReady"],
    eligiblePrecedingFamilies: ["footwork", "transition", "power"], contacts: [contact("back", 0, 1, 0)],
    staminaCost: 8, staminaDrainPerBeat: 3, balanceDemand: 0.18, cancelWindows: [[0.46, 0.58], [0.9, 1]],
    extensionInput: "power", validFollowUps: POWER_FOLLOWUPS, failureRecovery: "cleanGetUp",
    scoreProperties: { base: 92, musicality: 0.72, vocabulary: 0.65, originality: 0.5, technique: 0.72, execution: 0.58 }, crowdResponsePotential: 0.6,
  }),
  swipe: move({
    id: "swipe", displayName: "SWIPE", family: "power", difficulty: 0.62, durationBeats: 2,
    loopLength: 2, loopable: true, entryTags: ["floor", "powerReady"], exitTags: ["floor", "powerReady", "freezeReady"],
    eligiblePrecedingFamilies: ["footwork", "transition", "power"], contacts: [contact("leftPaw", 0, 0.3, -18), contact("rightPaw", 0.23, 0.57, 18), contact("leftPaw", 0.52, 0.82, -18), contact("rightPaw", 0.77, 1, 18, 0, "rightPaw-return")],
    staminaCost: 10, staminaDrainPerBeat: 4, balanceDemand: 0.3, cancelWindows: [[0.46, 0.56], [0.9, 1]],
    extensionInput: "power", validFollowUps: POWER_FOLLOWUPS, failureRecovery: "basicGoDown",
    scoreProperties: { base: 118, musicality: 0.72, vocabulary: 0.72, originality: 0.65, technique: 0.84, execution: 0.56 }, crowdResponsePotential: 0.72,
  }),
  windmill: move({
    id: "windmill",
    displayName: "WINDMILL",
    family: "power",
    difficulty: 0.68,
    durationBeats: 2,
    minimumDuration: 1,
    loopLength: 2,
    loopable: true,
    entryTags: ["floor", "powerReady"],
    exitTags: ["floor", "powerReady", "freezeReady", "momentum"],
    eligiblePrecedingFamilies: ["footwork", "transition", "power"],
    contacts: [
      contact("leftShoulder", 0, 0.199, -10, -3),
      contact("back", 0.2, 0.5, 0, -4),
      contact("rightShoulder", 0.501, 0.739, 10, -3),
      contact("leftPaw", 0.74, 1, -18),
    ],
    centerOfMassCurve: [[0, 0, -10], [0.25, 2, -12], [0.5, 0, -13], [0.75, -2, -12], [1, 0, -10]],
    staminaCost: 12,
    staminaDrainPerBeat: 5,
    balanceDemand: 0.36,
    cancelWindows: [[0.46, 0.57], [0.88, 1]],
    accentWindows: [0, 0.5, 1],
    extensionInput: "power",
    validFollowUps: POWER_FOLLOWUPS,
    failureRecovery: "basicGoDown",
    scoreProperties: { base: 142, musicality: 0.78, vocabulary: 0.76, originality: 0.68, technique: 0.9, execution: 0.58 },
    soundEvents: [{ at: 0, id: "moveStart" }, { at: 0.5, id: "powerExtend" }],
    crowdResponsePotential: 0.82,
  }),
  flare: move({
    id: "flare", displayName: "FLARE", family: "power", difficulty: 0.82, durationBeats: 2,
    loopLength: 2, loopable: true, entryTags: ["floor", "powerReady"], exitTags: ["floor", "powerReady", "freezeReady", "momentum"],
    eligiblePrecedingFamilies: ["footwork", "power"], contacts: [contact("leftPaw", 0, 0.38, -18), contact("rightPaw", 0.34, 0.7, 18), contact("leftPaw", 0.66, 1, -18, 0, "leftPaw-return")],
    staminaCost: 16, staminaDrainPerBeat: 6.5, balanceDemand: 0.48, cancelWindows: [[0.46, 0.56], [0.9, 1]], extensionInput: "power",
    validFollowUps: POWER_FOLLOWUPS, failureRecovery: "basicGoDown",
    scoreProperties: { base: 178, musicality: 0.72, vocabulary: 0.82, originality: 0.78, technique: 1, execution: 0.5 }, crowdResponsePotential: 0.92,
  }),
  headspin: move({
    id: "headspin", displayName: "HEADSPIN", family: "power", difficulty: 0.94, durationBeats: 2,
    loopLength: 2, loopable: true, entryTags: ["floor", "powerReady"], exitTags: ["floor", "freezeReady", "momentum"],
    eligiblePrecedingFamilies: ["power", "footwork"], contacts: [contact("head", 0, 1, 0)],
    staminaCost: 20, staminaDrainPerBeat: 8, balanceDemand: 0.68, cancelWindows: [[0.48, 0.55], [0.92, 1]], extensionInput: "power",
    validFollowUps: ["headstandFreeze", "babyFreeze", "cleanGetUp"], failureRecovery: "basicGoDown",
    scoreProperties: { base: 230, musicality: 0.76, vocabulary: 0.9, originality: 0.86, technique: 1, execution: 0.42 }, crowdResponsePotential: 1,
  }),

  babyFreeze: move({
    id: "babyFreeze", displayName: "BABY FREEZE", family: "freeze", difficulty: 0.38, durationBeats: 2,
    loopLength: 1, loopable: true, entryTags: ["floor", "freezeReady"], exitTags: ["floor", "freezeReady"],
    eligiblePrecedingFamilies: ["footwork", "power", "transition"], contacts: [contact("leftPaw", 0, 1, -9), contact("rightPaw", 0, 1, 8)],
    centerOfMassCurve: [[0, 0, -10], [0.2, 1, -13], [1, 0, -14]], staminaCost: 6, staminaDrainPerBeat: 2.2,
    balanceDemand: 0.3, cancelWindows: [[0.76, 1]], extensionInput: "freeze", validFollowUps: FREEZE_FOLLOWUPS,
    failureRecovery: "basicGoDown", scoreProperties: { base: 105, musicality: 0.9, vocabulary: 0.72, originality: 0.62, technique: 0.72, execution: 0.82 },
    soundEvents: [{ at: 0.18, id: "freeze" }], crowdResponsePotential: 0.78,
  }),
  chairFreeze: move({
    id: "chairFreeze", displayName: "CHAIR FREEZE", family: "freeze", difficulty: 0.58, durationBeats: 2,
    loopLength: 1, loopable: true, entryTags: ["floor", "freezeReady"], exitTags: ["floor", "freezeReady"],
    eligiblePrecedingFamilies: ["footwork", "power"], contacts: [contact("leftPaw", 0, 1, -9), contact("rightPaw", 0, 1, 8)],
    staminaCost: 8, staminaDrainPerBeat: 3, balanceDemand: 0.44, extensionInput: "freeze", validFollowUps: FREEZE_FOLLOWUPS,
    failureRecovery: "basicGoDown", scoreProperties: { base: 132, musicality: 0.86, vocabulary: 0.78, originality: 0.72, technique: 0.84, execution: 0.72 },
    soundEvents: [{ at: 0.18, id: "freeze" }], crowdResponsePotential: 0.86,
  }),
  turtleFreeze: move({
    id: "turtleFreeze", displayName: "TURTLE FREEZE", family: "freeze", difficulty: 0.64, durationBeats: 2,
    loopLength: 1, loopable: true, entryTags: ["floor", "freezeReady"], exitTags: ["floor", "freezeReady"],
    eligiblePrecedingFamilies: ["footwork", "power"], contacts: [contact("leftPaw", 0, 1, -10), contact("rightPaw", 0, 1, 10)],
    staminaCost: 9, staminaDrainPerBeat: 3.5, balanceDemand: 0.5, extensionInput: "freeze", validFollowUps: FREEZE_FOLLOWUPS,
    failureRecovery: "basicGoDown", scoreProperties: { base: 145, musicality: 0.82, vocabulary: 0.8, originality: 0.78, technique: 0.9, execution: 0.7 },
    soundEvents: [{ at: 0.18, id: "freeze" }], crowdResponsePotential: 0.9,
  }),
  headstandFreeze: move({
    id: "headstandFreeze", displayName: "HEADSTAND FREEZE", family: "freeze", difficulty: 0.78, durationBeats: 2,
    loopLength: 1, loopable: true, entryTags: ["floor", "freezeReady"], exitTags: ["floor", "freezeReady"],
    eligiblePrecedingFamilies: ["footwork", "power"], contacts: [contact("head", 0, 1, 0), contact("leftPaw", 0, 1, -10), contact("rightPaw", 0, 1, 10)],
    staminaCost: 12, staminaDrainPerBeat: 4.5, balanceDemand: 0.62, extensionInput: "freeze", validFollowUps: FREEZE_FOLLOWUPS,
    failureRecovery: "basicGoDown", scoreProperties: { base: 182, musicality: 0.88, vocabulary: 0.88, originality: 0.82, technique: 0.98, execution: 0.62 },
    soundEvents: [{ at: 0.18, id: "freeze" }], crowdResponsePotential: 1,
  }),
});

export const MOVE_IDS = Object.freeze(Object.keys(MOVE_CATALOG));
export const MOVE_FAMILIES = Object.freeze(["toprock", "transition", "footwork", "power", "freeze", "recovery"]);

export function getMoveDefinition(id) {
  return MOVE_CATALOG[id] ?? null;
}

export function movesByFamily(family) {
  return Object.values(MOVE_CATALOG).filter((moveDefinition) => moveDefinition.family === family);
}
